### ISSUE TITLE
Adding new PC to assets

### ISSUE THREAD

**Issue by nomish00** [skalg/Snipe-IT-PSAgent#1]
Hi, I had some problems adding new PC into assets to my snipe-it server. After configuration and starting agent some of the fields appears in the db but only as a custom fields, models, manufactures etc. Is there any possibility to add complete asset?

**Comment by 25hash** [comment]
Hello, Yes it's supposed to add the asset completely. If it's only creating the model but not the asset, it may have something to do with the $status_id variable. Be sure to assign a valid status id, you can test them with : http://snipeiturl/hardware/?status_id=5

**Comment by nomish00** [comment]
Status id is correct. For now it only fill out asset model in Settings>Assets Models. After starting agent I've got only "New Asset ID:" displayed but nothing more. Is it necessary to create additional client user in snipeit? I have clean install of latest version of snipeit.

**Comment by 25hash** [comment]
You'll have to adjust the $dbFields variables to match the one from your models. The $dbFields are the custom fields names associated to your computer model. https://snipe-it.readme.io/reference/updating-custom-fields

**Comment by nomish00** [comment]
Thank you, that was main problem. Moreover I'd like to add that when you have more network interfaces it's necessary to change MAC address field format (by default it's single MAC format).

**Comment by 25hash** [comment]
Yes indeed for the mac address field. It's better to have it as a text field to register all the available mac on the system. And to answer your previous question about the need to create a dedicated user for the update script. It's better, i've called it "Update Agent". You can easily differenciate the script from your actions and restrict the user permissions.
