### ISSUE TITLE
Error during asset update: Unable to connect to the remote server

### ISSUE THREAD

**Issue by ctsamuraix** [skalg/Snipe-IT-PSAgent#2]
Downloaded the script and updated it with the required api and url, but whenever I run it, I get the following:
_.\snipeit-asset-management.ps1
Asset name requires update: '' -> 'MYDEVICENAME'
Asset updated with ID: Error during asset update: Unable to connect to the remote server_

I can ping and ssh to my snipe-it server fine as well as access the web interface from this device. Not sure if I'm missing anything to allow that script to connect. I've tried the same on a few devices as well with the same result.

**Comment by 25hash** [comment]
Seams like you have access since its seeing that it needs update. Replace line 367 with :

`Write-Output "Asset name requires update: ID: $assetId '$($asset.name)' -> '$assetName'"`

Maybe there's something wrong with the id and it's not catching the exception.
Let me know if the id is detected correctly,

**Comment by ctsamuraix** [comment]
Unfortunately same issue. Although 367 seems to be the line for custom fields, but I tried it on that and the asset name line(360) as well to the same result. it did change the output slightly to the following
`Asset name requires update: ID:  '' -> 'MYDEVICENAME'
Asset updated with ID: Error during asset update: Unable to connect to the remote server`

Thanks for the super quick reply btw

**Comment by javiervalerocelada** [comment]
Hi!!! Someone can said if the script is working with new asset????

**Comment by 25hash** [comment]
> Hi!!! Someone can said if the script is working with new asset????

Normally yes, something may be malformed when the request is sent for this user, but so for i have it working daily on 400+ pc

**Comment by ctsamuraix** [comment]
I get the same error on an existing device I manually added to our inventory as well as one that I haven't.

**Comment by 25hash** [comment]
> Unfortunately same issue. Although 367 seems to be the line for custom fields, but I tried it on that and the asset name line(360) as well to the same result. it did change the output slightly to the following `Asset name requires update: ID: '' -> 'MYDEVICENAME' Asset updated with ID: Error during asset update: Unable to connect to the remote server`
> 
> Thanks for the super quick reply btw

Strange.. cause we know the API and URL are working since it's detecting the asset needs an update. But can't update it. Are you running Snipe 7.x or 6.x ? Don't know if they made any changes from 6 to 7, i'm still on 6...

**Comment by ctsamuraix** [comment]
> > Unfortunately same issue. Although 367 seems to be the line for custom fields, but I tried it on that and the asset name line(360) as well to the same result. it did change the output slightly to the following `Asset name requires update: ID: '' -> 'MYDEVICENAME' Asset updated with ID: Error during asset update: Unable to connect to the remote server`
> > Thanks for the super quick reply btw
> 
> Strange.. cause we know the API and URL are working since it's detecting the asset needs an update. But can't update it. Are you running Snipe 7.x or 6.x ? Don't know if they made any changes from 6 to 7, i'm still on 6...

Currently running Version v7.0.13 - build 15666

**Comment by 25hash** [comment]
I'm going to try with 7 in the next few days

**Comment by ctsamuraix** [comment]
Thanks. I'll keep fiddling on my end as well. It very well could be a difference in version.

**Comment by ctsamuraix** [comment]
Figured out what my initial issue was. Ended up playing around with the URL I was using. I was able to add additional custom fields and everything. Thanks for getting this working. 
(I did just start receiving different issues as another user but gonna say this is fixed and continue in that thread. Thanks!)
