### ISSUE TITLE
Not updating assets

### ISSUE THREAD

**Issue by RaheemJD** [skalg/Snipe-IT-PSAgent#3]
Script returns Asset Updated with ID: _______   . Just a blank space after, see screenshot below. Api & url is set aswell as custom fields.

![image](https://github.com/user-attachments/assets/d6e8aff6-8d7a-48a6-b51f-107d1adc7abb)

**Comment by ctsamuraix** [comment]
I had gotten it to work for about a week but noticed this morning that I'm getting the same thing as you all of a sudden.

**Comment by 25hash** [comment]
Hello, i've updated the script to include model and serial exclusion. And also fixed some issues and added more verbose debug. Let me know if this fixes it.

**Comment by ctsamuraix** [comment]
Figured out what _my_ issue was. I was attempting to add a search for installed printers that seems to have broken my version. Commented that out and I was able to successfully run the script again.
